# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2452133951785f05f7e7f15d3970cc26bd2f12c6dd653e0fbb108c61758be33b24bb70e77b81f801155f8991e76089d74bbdd801e5f01d70bbe7d0b89a9874ee

test:
  secret_key_base: 9215e4173d3479cdae47275b72da025b21c72ea0efa5e98161720db6f416e1f5094139d0c637ab6c6ba82bed072556b84abc9c52ca7eb3a1d6f463d96b02b8d5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
